---
abstract: 'Bindings for the OpenStack Compute API.'
author:
  - 'Naveed Massjouni <naveedm9@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OpenStack-Compute
requires:
  Any::Moose: 0
  App::Rad: 0
  App::Rad::Plugin::MoreHelp: 0
  HTTP::Request: 0
  JSON: 0
  LWP: 0
resources:
  bugtracker: http://github.com/ironcamel/Net-OpenStack-Compute/issues
  repository: git://github.com/ironcamel/Net-OpenStack-Compute.git
version: 1.0401
